In [7]:
import pandas as pd

df=pd.read_csv('서울특별시 공공자전거 대여이력 정보_2605.csv',encoding='cp949')
df.head(3).T

                            0                    1                    2
자전거번호               SPB-56805            SPB-60696            SPB-58865
대여일시      2026-05-01 00:00:16  2026-05-01 00:00:29  2026-05-01 00:00:27
대여 대여소번호                 2038                  588                  584
대여 대여소명              동작역 7번출구              뚝섬 유원지역             광진광장 교통섬
대여거치대                       0                    0                    0
반납일시      2026-05-01 00:01:29  2026-05-01 00:01:51  2026-05-01 00:02:08
반납대여소번호                2038.0                588.0                516.0
반납대여소명               동작역 7번출구              뚝섬 유원지역              광진메디칼 앞
반납거치대                     0.0                  0.0                  0.0
이용시간(분)                     1                    1                    1
이용거리(M)                   0.0                 40.0                88.16
생년                     2008.0               1993.0               1968.0
성별                          M                  NaN                    M
이용자종류                     내국인                  내국인                  내국인
대여대여소ID                ST-696               ST-483               ST-445
반납대여소ID                ST-696               ST-483               ST-114

In [6]:
df.describe()

,대여 대여소번호,대여거치대,반납대여소번호,반납거치대,이용시간(분),이용거리(M),생년
count,4.029272e+06,4.029272e+06,4.008345e+06,4.005343e+06,4.029272e+06,4.029272e+06,3.946539e+06
mean,2.411349e+03,2.890659e+00,2.410098e+03,2.866355e+00,2.242909e+01,2.529479e+03,1.988771e+03
std,1.711476e+03,1.666792e+01,1.710479e+03,1.659979e+01,3.245189e+01,3.176057e+03,1.583101e+01
min,1.020000e+02,0.000000e+00,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,9.330000e+02,0.000000e+00,9.380000e+02,0.000000e+00,6.000000e+00,7.937700e+02,1.980000e+03
50%,1.996000e+03,0.000000e+00,1.994000e+03,0.000000e+00,1.200000e+01,1.472670e+03,1.992000e+03
75%,3.929000e+03,0.000000e+00,3.931000e+03,0.000000e+00,2.800000e+01,2.909770e+03,1.998000e+03
max,9.980000e+03,9.900000e+01,9.998000e+03,9.900000e+01,4.148000e+03,1.550010e+05,2.099000e+03